name: gnome-robots
adopt-info: gnome-robots
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

slots:
  # for GtkApplication registration
  gnome-robots:
    interface: dbus
    bus: session
    name: org.gnome.Robots

apps:
  gnome-robots:
    extensions: [gnome-3-34]
    command: usr/bin/gnome-robots
    plugs:
      - gsettings
      - pulseaudio
    desktop: usr/share/applications/org.gnome.Robots.desktop
    common-id: org.gnome.Robots.desktop

parts:
  libcanberra:
    source: git://git.0pointer.de/libcanberra
    source-type: git
    plugin: autotools
    configflags:
      - --prefix=/snap/gnome-robots/current/usr
      - --enable-pulse
      - --enable-gstreamer
      - --enable-gtk3
      - --enable-alsa
      - --disable-oss
    organize:
      snap/gnome-robots/current/usr: usr
    build-packages:
      - libltdl-dev
      - libasound2-dev
      - libvorbis-dev
      - libgtk-3-dev
      - libtdb-dev
      - libpulse-dev
      - libgstreamer1.0-dev
      - libudev-dev
      - gtk-doc-tools

  gnome-robots:
    after: [libcanberra]
    source: https://gitlab.gnome.org/GNOME/gnome-robots.git
    source-type: git
    source-branch: gnome-3-38
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.Robots$|=${SNAP}/meta/gui/org.gnome.Robots.svg|g' data/org.gnome.Robots.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/org.gnome.Robots.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-robots/current/usr]
    parse-info: [usr/share/metainfo/org.gnome.Robots.appdata.xml]
    organize:
      snap/gnome-robots/current/usr: usr
    build-packages:
      - appstream-util
      - gettext
      - intltool
      - libglib2.0-dev
      - libgnome-games-support-1-dev
      - libgsound-dev
      - libgtk-3-dev
      - librsvg2-dev
      - yelp-tools

  libraries:
    plugin: nil
    stage-packages:
      - libgnome-games-support-1-3
      - libgee-0.8-2
      - libgsound0
    prime:
      - "usr/lib/*/libgnome-games-support-1.so.*"
      - "usr/lib/*/libgee-0.8.so.*"
      - "usr/lib/*/libgsound.so.*"
