name: gnome-robots
version: 3.22.2
summary: Avoid the robots and make them crash into each other
description: |
  It is the distant future – the year 2000. Evil robots are trying to kill you.
  Avoid the robots or face certain death.

  Fortunately, the robots are extremely stupid and will always move directly
  towards you. Trick them into colliding into each other, resulting in their
  destruction, or into the junk piles that result. You can defend yourself by
  moving the junk piles, or escape to safety with your handy teleportation
  device.

  Your supply of safe teleports is limited, and once you run out, teleportation
  could land you right next to a robot, who will kill you. Survive for as long
  as possible!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-robots:
    interface: dbus
    bus: session
    name: org.gnome.robots

apps:
  gnome-robots:
    command: desktop-launch gnome-robots
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - pulseaudio
      - unity7
      - wayland
    desktop: usr/share/applications/gnome-robots.desktop

parts:
  libcanberra:
    source: git://git.0pointer.de/libcanberra
    source-type: git
    plugin: autotools
    configflags:
      - --prefix=/snap/gnome-robots/current/usr
      - --enable-pulse
      - --enable-gstreamer
      - --enable-gtk3
      - --enable-alsa
      - --disable-oss
    organize:
      snap/gnome-robots/current/usr: usr
    build-packages:
      - libltdl-dev
      - libasound2-dev
      - libvorbis-dev
      - libgtk-3-dev
      - libtdb-dev
      - libpulse-dev
      - libgstreamer1.0-dev
      - gtk-doc-tools

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  gnome-robots:
    after: [desktop-gnome-platform, libcanberra]
    source: https://gitlab.gnome.org/GNOME/gnome-robots.git
    source-type: git
    source-tag: 3.22.2
    override-build: |
      sed -i.bak -e 's|=gnome-robots$|=${SNAP}/meta/gui/gnome-robots.png|g' data/gnome-robots.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/48x48/gnome-robots.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/gnome-robots.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: autotools
    configflags: [--prefix=/snap/gnome-robots/current/usr]
    organize:
      snap/gnome-robots/current/usr: usr
    build-packages:
      - appstream-util
      - gettext
      - intltool
      - libglib2.0-dev
      - libgnome-games-support-1-dev
      - libgtk-3-dev
      - librsvg2-dev
      - yelp-tools
  libraries:
    plugin: nil
    stage-packages:
      - libgnome-games-support-1-3
      - libgee-0.8-2
    prime:
      - "usr/lib/*/libgnome-games-support-1.so.*"
      - "usr/lib/x86_64-linux-gnu/libgee-0.8.so.*"
